src/apps/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register('users', viewset=views.UserViewSet)
router.register('calc_simple', viewset=views.CalcSimpleViewSet)
router.register('coureur', viewset=views.CoureurViewSet)
router.register('categorie', viewset=views.CategorieViewSet)
router.register('course', viewset=views.CourseViewSet)
app_name = "api"

urlpatterns = [
    path('api/', include(router.urls)),
]

src/apps/authentification/urls.py
from django.urls import path
from . import views

app_name = 'authentification'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('users/', views.page_users, name='page_users')
]

src/apps/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "main"

urlpatterns = [
    path('', views.redirection, name='redirection'),
    path('tp_excel/', views.page_main, name='index'),
]

src/apps/tp1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "tp1"

urlpatterns = [
    path('', views.page_tp1, name='page_tp1'),
]

src/apps/tp2/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "tp2"

urlpatterns = [
    path('', views.page_tp2, name='page_tp2'),
]

src/tp_excel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('tp_excel/', include('apps.api.urls')),
    path('tp_excel/auth/', include('apps.authentification.urls')),
    path('tp_excel/tp1/', include('apps.tp1.urls')),
    path('tp_excel/tp2/', include('apps.tp2.urls')),
]

src/apps/api/models.py
from django.db import models

# Create your models here.

class CalcSimple(models.Model):
    id_calc_simple = models.AutoField(primary_key=True)
    produit = models.CharField(max_length=50, blank=True, null=True)
    nb_achats = models.IntegerField(blank=True, null=True)
    nb_ventes = models.IntegerField(blank=True, null=True)
    stock = models.IntegerField(blank=True, null=True)
    prix_unitaire = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    ca = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)

    class Meta:
        db_table = 'calc_simple'

class Course(models.Model):
    id_course = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=100, blank=True, null=True)
    prix_15 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    prix_20 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    class Meta:
        db_table = 'course'

    def __str__(self):
        return self.nom if self.nom else f"Course {self.id_course}"


class Categorie(models.Model):
    id_categorie = models.AutoField(primary_key=True)
    annee = models.DateField(blank=True, null=True)
    code_categorie = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        db_table = 'categorie'

    def __str__(self):
        return self.code_categorie if self.code_categorie else f"Categorie {self.id_categorie}"


class Coureur(models.Model):
    id_coureur = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=100, blank=True, null=True)
    prenom = models.CharField(max_length=100, blank=True, null=True)
    sexe = models.CharField(max_length=10, blank=True, null=True)
    date_de_naissance = models.DateField(blank=True, null=True)
    categorie = models.ForeignKey(Categorie, on_delete=models.SET_NULL, blank=True, null=True)
    taille_tee_shirt = models.CharField(max_length=10, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, blank=True, null=True)
    prix_club = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    repas_avant_course = models.BooleanField(default=False, blank=True, null=True)
    prix_du_repas_avant_course = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    repas_apres_course = models.BooleanField(default=False, blank=True, null=True)
    prix_du_repas_apres_course = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    total_coureur = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    class Meta:
        db_table = 'coureur'

    def __str__(self):
        return f"{self.nom} {self.prenom}" if self.nom and self.prenom else f"Coureur {self.id_coureur}"

src/apps/authentification/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    # Add additional fields here if necessary
    pass

src/apps/tp2/models.py
from django.db import models

# Create your models here.

src/apps/api/views.py
from django.shortcuts import render
from rest_framework import viewsets
from django.contrib.auth import get_user_model
from .serializers import *
from .models import *

User = get_user_model()


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class CalcSimpleViewSet(viewsets.ModelViewSet):

    queryset = CalcSimple.objects.all()
    serializer_class = CalcSimpleSerializer

class CourseViewSet(viewsets.ModelViewSet):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer

class CategorieViewSet(viewsets.ModelViewSet):
    queryset = Categorie.objects.all()
    serializer_class = CategorieSerializer

class CoureurViewSet(viewsets.ModelViewSet):
    queryset = Coureur.objects.all()
    serializer_class = CoureurSerializer

src/apps/authentification/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages




def login_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('tp1:page_tp1'))
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        print(f"Auth en cours de user {username}")

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('tp1:page_tp1'))
        else:
            messages.error(request, ("Identifiant et/ou mot de passe incorrect(s)"))
            return redirect(reverse('authentification:login'))
    else:
        return render(request, 'authentification/login.html')



def logout_view(request):
    logout(request)
    messages.success(request, ("Session déconnectée"))
    return redirect('authentification:login')


@login_required
def page_users(request):
    return render(request, 'authentification/users.html')

src/apps/main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def redirection(request):
    return HttpResponseRedirect(reverse('main:index'))


@login_required
def page_main(request):
    return render(request, 'main/index.html')

src/apps/tp1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required
def page_tp1(request):
    return render(request, 'tp1/tp1.html')

src/apps/tp2/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def page_tp2(request):
    return render(request, 'tp2/tp2.html')

src/apps/authentification/templates/authentification/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="w-50 mx-auto text-center">
    {% if messages %}
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">Identifiant ou mot de passe incorrect</div>
    {% endif %}
    {% if next %}
    {% if user.is_authenticated %}
    <div class="alert alert-warning" role="alert">Vous n'avez pas accès à cette page</div>
    {% else %}

    {% endif %}
    {% endif %}
</div>


<div class="container text-center mt-5">
    <div class="row justify-content-center">
        <div class="col-md-4 border rounded shadow border-secondary p-4">
            <div class="texte-bleu fw-bold fs-3 mb-4">Bienvenue</div>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label texte-bleu fs-6">Identifiant</label>
                    <input id="username" class="form-control" type="text" name="username" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label texte-bleu fs-6">Mot de passe</label>
                    <input id="password" type="password" class="form-control" name="password" required>
                </div>
                <button type="submit" class="btn btnsubmit mt-3 w-100">Se connecter</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

src/apps/authentification/templates/authentification/register.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <title>Register</title>
    </head>

    <body>
        <h2>Register</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Register</button>
        </form>
        <p>Already have an account? <a href="{% url 'authentification:login' %}">Login here</a></p>
    </body>

</html>

src/apps/authentification/templates/authentification/users.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">

    {% include "modal.html" %}

    <div class="row justify-content-center mt-3">
        <div class="col-md-7 alertPlaceholder"></div>
    </div>


    <div class="row justify-content-center mt-3">
        <button id="add-user" class="col-md-4 btn btnsubmit mt-3">Ajouter un utilisateur</button>
        <div class="col-md-9 mt-4">
            <table id="usersTable" class="display" width="100%">
                <thead>
                    <tr>
                        <th>Identifiant</th>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Mail</th>
                        <th>Rôle</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    const userId = {{ user.id }};
    const fr_url = "{% static 'librairie/datatables/fr_fr.json' %}";
    const user_group = "{{ user_group }}";
    console.log(userId)
</script>
<script src="{% static 'js/forms.js' %}"></script>
<script src="{% static 'authentification/js/users.js' %}"></script>
{% endblock %}

src/apps/main/templates/main/index.html
{% extends 'base.html' %}
{%load static %}

{% block content %}
<h1>Hey</h1>
{% endblock %}

src/apps/tp1/templates/tp1/tp1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container my-5">
    <!-- Tabs Navigation -->
    <h5 class="text-center texte-bleu">Les bases essentielles à connaître</h5>
    <ul class="nav nav-tabs justify-content-center mt-4" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="tab1-tab" data-bs-toggle="tab" data-bs-target="#tab1" type="button"
                role="tab" aria-controls="tab1" aria-selected="true">
                Calculs simples
            </button>
        </li>
    <!-- <li class="nav-item" role="presentation">
            <button class="nav-link" id="tab2-tab" data-bs-toggle="tab" data-bs-target="#tab2" type="button" role="tab"
                aria-controls="tab2" aria-selected="false">
                Référence absolue
            </button>
        </li>-->
    </ul>

    <!-- Tabs Content -->
    <div class="tab-content my-4" id="myTabContent">


        <div class="tab-pane fade show active " id="tab1" role="tabpanel" aria-labelledby="tab1-tab">
            <div class="d-flex flex-column align-items-center ">
                <button id="addRowButton" class="btn btnsubmit mb-3">+</button>
                <div id="table_calc_simple"></div>
            </div>
        </div>


        <div class="tab-pane fade " id="tab2" role="tabpanel" aria-labelledby="tab2-tab">
            <div class="d-flex flex-column align-items-center">
                <button id="addRowButton" class="btn btnsubmit mb-3">+</button>
                <div id="table_ref_absolue"></div>
            </div>


        </div>
    </div>
</div>


{% endblock %}
{% block script %}
<script>
    const userId = {{ user.id }};
    const fr_url = "{% static 'librairie/datatables/fr_fr.json' %}";
    const user_group = "{{ user_group }}";
    const csrfToken = "{{ csrf_token }}";
    console.log(userId)
</script>
<script src="{% static 'js/forms.js' %}"></script>
<script src="{% static 'tp1/js/tp1.js' %}"></script>
{% endblock %}

src/apps/tp2/templates/tp2/tp2.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<div class="container my-5">
    {% include "modal.html" %}

    <div class="row justify-content-center mt-3">
        <div class="col-md-7 alertPlaceholder"></div>
    </div>
    <!-- Tabs Navigation -->
    <h5 class="text-center texte-bleu">Grand Raid</h5>
    <ul class="nav nav-tabs justify-content-center mt-4" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="tab1-tab" data-bs-toggle="tab" data-bs-target="#tab1" type="button"
                role="tab" aria-controls="tab1" aria-selected="true">
                Tableau de synthèse
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="tab2-tab" data-bs-toggle="tab" data-bs-target="#tab2" type="button" role="tab"
                aria-controls="tab2" aria-selected="false">
                Coureurs
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="tab3-tab" data-bs-toggle="tab" data-bs-target="#tab3" type="button" role="tab"
                aria-controls="tab3" aria-selected="false">
                Courses
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="tab4-tab" data-bs-toggle="tab" data-bs-target="#tab4" type="button" role="tab"
                aria-controls="tab4" aria-selected="false">
                Catégories
            </button>
        </li>
    </ul>

 
    <div class="tab-content my-4" id="myTabContent">

        <div class="tab-pane fade show active" id="tab1" role="tabpanel" aria-labelledby="tab1-tab">
            <div class="d-flex flex-column align-items-center">
                <div id="table_synthese" class="container">
              
                    <div class="row">
                        
                        <div class="col-md-6">
                            <table id="runnersTable" class="table table-striped text-center">
                                <thead>
                                    <tr>
                                        <th>Course</th>
                                        <th>Nombre de coureur</th>
                                    </tr>
                                </thead>
                                <tbody>
                                 
                                </tbody>
                            </table>
                        </div>

                    
                        <div class="col-md-6">
                            <table id="totalCoureurTable" class="table table-striped text-center">
                                <thead>
                                    <tr>
                                        <th>Total Club</th>
                                    </tr>
                                </thead>
                                <tbody>
                                
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="tab-pane fade " id="tab2" role="tabpanel" aria-labelledby="tab2-tab">
            <div class="d-flex flex-column align-items-center">
                <button id="add-coureur" class="btn btnsubmit mb-3">+</button>
                <div id="table_coureur">
                    <table id="coureurTable" class="display" width="100%">
                    </table>
                </div>
            </div>
        </div>

        <div class="tab-pane fade " id="tab3" role="tabpanel" aria-labelledby="tab3-tab">
            <div class="d-flex flex-column align-items-center">
                <button id="add-course" class="btn btnsubmit mb-3">+</button>

                <div id="table_course">
                    <table id="courseTable" class="display" width="100%">
                    </table>
                </div>
            </div>
        </div>

        <div class="tab-pane fade " id="tab4" role="tabpanel" aria-labelledby="tab4-tab">
            <div class="d-flex flex-column align-items-center">
                <button id="add-categorie" class="btn btnsubmit mb-3">+</button>
                <div id="table_categorie">
                    <table id="categorieTable" class="display" width="100%">
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>


{% endblock %}
{% block script %}
<script>
    const userId = {{ user.id }};
    const fr_url = "{% static 'librairie/datatables/fr_fr.json' %}";
    const user_group = "{{ user_group }}";
    const csrfToken = "{{ csrf_token }}";
    console.log(userId)
</script>
<script src="{% static 'js/forms.js' %}"></script>
<script src="{% static 'tp2/js/tp2.js' %}"></script>
{% endblock %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <title>TPZZZZ EXCEL</title>
        <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}" />
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <link rel="stylesheet" href="{% static 'librairie/bootstrap/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'librairie/datatables/datatables.min.css' %}" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/handsontable/dist/handsontable.full.min.css">

        {% block head %}{% endblock %}
    </head>

    <body>

        {% include 'navbar.html' %}

        {% block content %}{% endblock %}
        <script src="{% static 'librairie/jquery/jquery-3.7.min.js' %}"></script>
        <script src="{% static 'librairie/popper/popper.min.js' %}"></script>
        <script src="{% static 'librairie/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'librairie/datatables/datatables.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/handsontable/dist/handsontable.full.min.js"></script>
        {% block script %}{% endblock %}
    </body>

</html>

src/templates/modal.html
<div class="modal fade" id="modalForm" tabindex="-1" role="dialog" aria-labelledby="modalForm" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle">Titre modal</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body"></div>
        </div>
    </div>
</div>

src/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#"><img class="mx-3" src="" style="max-height: 50px;" /></a>



    <div class="navbar-center">
        <a href="{% url 'main:index' %}">
            <h1 class="d-inline-block align-middle titre">
                <span class="texte-bleu">TP EXCEL</span>
            </h1>
        </a>
    </div>


    {% if user.is_authenticated %}
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">

        <ul class="navbar-nav fs-5">
            {% if user.is_superuser %}
            <li class="nav-item dropdown">
                <a class="nav-link" href="{% url 'authentification:page_users' %}"><img class=""
                        style="max-height: 30px; margin-top:-10px" src="{% static 'images/users.png' %}" alt=""></a>
            </li>
            {% endif %}

            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" id="userDropdown" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    <img class="mx-1" src="{% static 'images/burger-bar.png' %}" alt="user icon"
                        style="max-height: 35px; margin-top:-10px" />
                </a>
                <ul class="dropdown-menu dropdown-menu-end fs-6 mr-5 text-center" aria-labelledby="userDropdown">
                    <li>
                        <p class="dropdown-item-text texte_bleu"
                            style="text-transform: uppercase; margin-bottom: -5px; white-space: nowrap;">
                            <img class="mx-1" src="{% static 'images/user_icon_no_circle.png' %}" alt="user icon"
                                style="max-height: 15px; margin-top: -5px;" />
                            {{ user.get_username }}
                        </p>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item texte-bleu" href="{% url 'tp1:page_tp1' %}">Les bases essentielles à
                            connaître</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item texte-bleu" href="{% url 'tp1:page_tp1' %}">Mise en forme conditionnelle
                            et la liste deroulante</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item texte-bleu" href="{% url 'tp1:page_tp1' %}">Tableaux et graphiques
                            croises dynamiques</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item texte-bleu" href="{% url 'tp1:page_tp1' %}">Cas facturation</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item texte-bleu" href="{% url 'tp1:page_tp1' %}">Complet operation base</a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item texte-bleu" href="{% url 'tp1:page_tp1' %}">enonce CA par produit</a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item texte-bleu" href="{% url 'tp1:page_tp1' %}">revision statistiques</a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item texte-bleu" href="{% url 'tp2:page_tp2' %}">Grand Raid</a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <div class="mx-5">
                            <a href="{% url 'authentification:logout' %}?next={{ request.path }}"><img class=""
                                    src="{% static 'images/logout.png' %}" alt="logout" style="max-height: 20px;" /></a>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    {% endif %}

</nav>
<hr class="" style="margin-top: -5px">